version: '3.1'
services:
  db:
    image: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    # volumes:
    #   - $HOME/Desktop/MySQL-Snippets/school.sql:/school.sql
